# Generated by Django 4.2.1 on 2023-05-15 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.CharField(choices=[('question', 'سؤال'), ('post', 'منشور'), ('article', 'مقالة')], max_length=150, verbose_name='نوع المنشور')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المنشور')),
                ('content', models.TextField(verbose_name='محتوى المنشور')),
                ('likes', models.IntegerField(default=0, verbose_name='الإعجاب')),
                ('dislikes', models.IntegerField(default=0, verbose_name='ديسلايك')),
                ('date_published', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'منشور',
                'verbose_name_plural': 'المنشورات',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='التعليق')),
                ('date_published', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='المنشور')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
            },
        ),
    ]
