# Generated by Django 4.2.1 on 2023-05-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='p_type',
            field=models.CharField(choices=[('question', 'سؤال'), ('post', 'منشور'), ('article', 'مقالة')], max_length=60, verbose_name='نوع المنشور'),
        ),
    ]
