# Generated by Django 4.2.1 on 2023-05-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='post.category', verbose_name='الأقسام'),
        ),
    ]
